name: umuragizi
description: "Une application mobile moderne de gestion d'élevage développée avec Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  image_picker: ^1.0.4
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^17.1.3
  permission_handler: ^11.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  fl_chart: ^0.66.2
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.5
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  http: ^1.6.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.5
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/